[tools]
bat = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
herdr = "latest"
jq = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
yazi = "latest"
zoxide = "latest"
